LCAM-273-CC-Schemas
ministryofjustice/laa-crown-court-proceeding pull request #23
Opened 2022-10-31 11:25 UTC by loganathanMOJ

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-273)

Describe what you did and why.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] GitHub should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2022-11-01 13:27 UTC, Mhowell494 requested changes

2022-11-01 13:27 UTC, Mhowell494 commented on crown-court-proceeding/src/main/resources/schemas/apiCheckCrownCourtActionsRequest.json
> +    "FinancialAssessment": {
Can we make this lower case like the other fields? Same with IOJAppeal

2022-11-01 13:27 UTC, Mhowell494 commented on crown-court-proceeding/src/main/resources/schemas/common/apiFinancialAssessment.json
> +    "fassInitStatus": {
Can we just call this `initStatus`?

2022-11-01 13:27 UTC, Mhowell494 commented on crown-court-proceeding/src/main/resources/schemas/common/apiFinancialAssessment.json
> +    "fassFullStatus": {
Can we just call this `fullStatus`?

2022-11-01 13:27 UTC, Mhowell494 commented on crown-court-proceeding/src/main/resources/schemas/common/apiFinancialAssessment.json
> +  "required": ["initResult", "fassInitStatus", "fullResult", "fassFullStatus"]
It's possible there might not be a `fullResult` and `fassFullStatus` if it's an initial assessment

2022-11-01 13:27 UTC, Mhowell494 commented on crown-court-proceeding/src/main/resources/schemas/apiCheckCrownCourtActionsResponse.json
> +      "format": "date-time"
Can we simplify the names of the fields? It seems redundant to prepend each with cc when they're in the Crown Court Response object

2022-11-02 09:47 UTC, loganathanMOJ commented on crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/MagCourtOutcome.java
> +                .filter(f -> f.outcome.equals(outcome))
Fixed now

2022-11-02 09:47 UTC, loganathanMOJ commented on crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/CurrentStatus.java
> + * static data migrated from TOGDATA.HARDSHIP_REVIEW_STATUSES,
Thanks. Fixed now

2022-11-02 09:48 UTC, loganathanMOJ commented on crown-court-proceeding/src/main/resources/schemas/apiCheckCrownCourtActionsRequest.json
> +    "decisionReason": {
Thanks. Fixed now

2022-11-02 09:49 UTC, loganathanMOJ commented on crown-court-proceeding/src/main/resources/schemas/common/apiCrownCourtOverview.json
> +  "id": "apiCrownCourtOverview.json",
Removed apiCrownCourtOverview.json from schemas

2022-11-02 09:51 UTC, loganathanMOJ commented on crown-court-proceeding/src/main/resources/schemas/apiCheckCrownCourtActionsRequest.json
> +    "dateReceived": {
We need this filed for "determine_crown_reporder_date" stored procedure

2022-11-03 11:16 UTC, Mhowell494 approved these changes

2022-11-03 13:07 UTC, merged