LCAM-219|Determine CC Rep Order Decision
ministryofjustice/laa-crown-court-proceeding pull request #26
Opened 2022-11-14 09:48 UTC by venkat980

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-219)

Migrate business rules for determining the Crown Court Rep Order decision as part of the check crown court actions.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] GitHub should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2022-11-15 14:30 UTC, Mhowell494 requested changes
Overall, great work. I've added a few comments and I'd also like to see the code coverage improved slightly, as we're close to 100%. There are just a few branches that remain uncovered.

2022-11-15 14:30 UTC, Mhowell494 commented on crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/CrownCourtProceedingServiceTest.java
> +    @Spy
Doesn't look like we're making use of this annotation, so it can be removed.

2022-11-15 22:15 UTC, venkat980 commented on crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/CrownCourtProceedingService.java
>  public class CrownCourtProceedingService {
Done

2022-11-16 11:16 UTC, msahilan07 approved these changes

2022-11-16 12:56 UTC, merged